name: Build Android APK (EAS)

on:
  workflow_dispatch: # Allows you to manually trigger the build from GitHub
  push:
    branches:
      - main # Automatically runs every time you push code to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout repository code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 📱 Setup EAS CLI with Expo Token
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install project dependencies
        run: npm ci

      - name: 🚀 Trigger EAS APK Build
        run: eas build -p android --profile preview --non-interactive
